# Generated by Django 3.1.1 on 2020-10-22 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('caracteristica_1', models.CharField(max_length=200)),
                ('caracteristica_2', models.CharField(max_length=200)),
                ('caracteristica_3', models.CharField(max_length=200)),
                ('caracteristica_4', models.CharField(max_length=200)),
                ('caracteristica_5', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
