# Generated by Django 3.1.1 on 2020-10-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_promociones_inicio_promociones_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='nombre',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
