# Generated by Django 3.1.2 on 2020-10-30 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('imagen_id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('noticia_id', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=50)),
                ('imagen_id', models.ForeignKey(default='default.png', on_delete=django.db.models.deletion.SET_DEFAULT, to='noticias.imagen')),
            ],
        ),
    ]
