# Generated by Django 3.1.2 on 2020-10-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='noticia_id',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
