# Generated by Django 3.1.2 on 2020-10-30 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_auto_20201029_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='imagen_id',
            new_name='imagen',
        ),
    ]
